//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee1
    {
        public int eid { get; set; }
        public string ename { get; set; }
        public string desigination { get; set; }
        public Nullable<decimal> salary { get; set; }
    }
}
